// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using forms.WebAPI.Data;

namespace forms.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("forms.WebAPI.Model.Answer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormularioID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PossibilityAnswerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descriptionValueAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("questionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerID");

                    b.HasIndex("FormularioID");

                    b.HasIndex("PossibilityAnswerID");

                    b.HasIndex("UserID");

                    b.HasIndex("questionID");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Creator", b =>
                {
                    b.Property<int>("CreatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("institution")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("CreatorID");

                    b.ToTable("Creator");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Formulario", b =>
                {
                    b.Property<int>("FormularioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("theme")
                        .HasColumnType("TEXT");

                    b.Property<string>("version")
                        .HasColumnType("TEXT");

                    b.HasKey("FormularioID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Formulario");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Matrix", b =>
                {
                    b.Property<int>("MatrixID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormularioID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descriptionMatrix")
                        .HasColumnType("TEXT");

                    b.Property<int>("positionMatrix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("possibilityAnswerMatrix")
                        .HasColumnType("TEXT");

                    b.HasKey("MatrixID");

                    b.HasIndex("FormularioID");

                    b.ToTable("Matrix");
                });

            modelBuilder.Entity("forms.WebAPI.Model.PossibilityAnswer", b =>
                {
                    b.Property<int>("PossibilityAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormularioID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatrixID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descriptionValuePossibilityAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("questionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PossibilityAnswerID");

                    b.HasIndex("FormularioID");

                    b.HasIndex("MatrixID");

                    b.HasIndex("questionID");

                    b.ToTable("PossibilityAnswer");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Question", b =>
                {
                    b.Property<int>("questionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormularioID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatrixID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("answerDependency")
                        .HasColumnType("TEXT");

                    b.Property<string>("className")
                        .HasColumnType("TEXT");

                    b.Property<string>("condiction")
                        .HasColumnType("TEXT");

                    b.Property<string>("descriptionValueQuetion")
                        .HasColumnType("TEXT");

                    b.Property<string>("erroText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("flagDependency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("help")
                        .HasColumnType("TEXT");

                    b.Property<string>("icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("label")
                        .HasColumnType("TEXT");

                    b.Property<string>("placeHolder")
                        .HasColumnType("TEXT");

                    b.Property<string>("positionQuetion")
                        .HasColumnType("TEXT");

                    b.Property<string>("quetionDependency")
                        .HasColumnType("TEXT");

                    b.Property<string>("regex")
                        .HasColumnType("TEXT");

                    b.Property<string>("subType")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("questionID");

                    b.HasIndex("FormularioID");

                    b.HasIndex("MatrixID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("forms.WebAPI.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("institution")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("forms.WebAPI.Model.UserFormulario", b =>
                {
                    b.Property<int>("UserFormularioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormularioID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserFormularioID");

                    b.HasIndex("FormularioID");

                    b.HasIndex("UserID");

                    b.ToTable("UserFormulario");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Answer", b =>
                {
                    b.HasOne("forms.WebAPI.Model.Formulario", "Formulario")
                        .WithMany()
                        .HasForeignKey("FormularioID");

                    b.HasOne("forms.WebAPI.Model.PossibilityAnswer", "PossibilityAnswer")
                        .WithMany()
                        .HasForeignKey("PossibilityAnswerID");

                    b.HasOne("forms.WebAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.HasOne("forms.WebAPI.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("questionID");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Formulario", b =>
                {
                    b.HasOne("forms.WebAPI.Model.Creator", null)
                        .WithMany("Formulario")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("forms.WebAPI.Model.Matrix", b =>
                {
                    b.HasOne("forms.WebAPI.Model.Formulario", "Formulario")
                        .WithMany("Matrix")
                        .HasForeignKey("FormularioID");
                });

            modelBuilder.Entity("forms.WebAPI.Model.PossibilityAnswer", b =>
                {
                    b.HasOne("forms.WebAPI.Model.Formulario", "Formulario")
                        .WithMany()
                        .HasForeignKey("FormularioID");

                    b.HasOne("forms.WebAPI.Model.Matrix", "Matrix")
                        .WithMany()
                        .HasForeignKey("MatrixID");

                    b.HasOne("forms.WebAPI.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("questionID");
                });

            modelBuilder.Entity("forms.WebAPI.Model.Question", b =>
                {
                    b.HasOne("forms.WebAPI.Model.Formulario", "Formulario")
                        .WithMany()
                        .HasForeignKey("FormularioID");

                    b.HasOne("forms.WebAPI.Model.Matrix", "Matrix")
                        .WithMany()
                        .HasForeignKey("MatrixID");
                });

            modelBuilder.Entity("forms.WebAPI.Model.UserFormulario", b =>
                {
                    b.HasOne("forms.WebAPI.Model.Formulario", "Formulario")
                        .WithMany()
                        .HasForeignKey("FormularioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("forms.WebAPI.Model.User", "User")
                        .WithMany("UserFormulario")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
